### ISSUE TITLE
max() arg is an empty sequence

### ISSUE THREAD

**Issue by adeschen** [RabadanLab/arcasHLA#10]
Hi,

We ran arcasHLA on multiple samples. Only one sample failed. The error is posted bellow. 

Best,
Astrid

[genotype] Pairs by % explained reads:
                allele pair                     explained
                C*04:01:81, C*04:339:02             87.94%
                C*04:04:02, C*04:339:02             87.94%
Traceback (most recent call last):
  File "./scripts/genotype.py", line 917, in <module>
    args.zygosity_threshold)
  File "./scripts/genotype.py", line 585, in genotype_gene
    zygosity_threshold)
  File "./scripts/genotype.py", line 490, in predict_genotype
    max_prior = max(pair_prior.values())
ValueError: max() arg is an empty sequence

**Comment by maggiepie17** [comment]
I have the same issue. See error below:

[genotype] Quantifying allele transcript abundance
[genotype] EM converged after {iterations} iterations

[genotype] Top alleles by abundance:
                allele                  abundance
                C*16:150                   41.67%
                C*12:08                    29.17%
                C*12:188                   29.17%

[genotype] Pairs by % explained reads:
                allele pair                     explained
                C*12:08, C*16:150                   89.47%
                C*12:188, C*16:150                  89.47%
                C*12:188, C*12:08                   63.16%
Traceback (most recent call last):
  File "/project/ibilab/projects/Saar_Gill_scRNAseq_macrophag_2019_03/large_data/arcasHLA/scripts/genotype.py", line 719, in <module>
    args.zygosity_threshold)
  File "/project/ibilab/projects/Saar_Gill_scRNAseq_macrophag_2019_03/large_data/arcasHLA/scripts/genotype.py", line 434, in genotype_gene
    zygosity_threshold)
  File "/project/ibilab/projects/Saar_Gill_scRNAseq_macrophag_2019_03/large_data/arcasHLA/scripts/genotype.py", line 339, in predict_genotype
    max_prior = max(pair_prior.values())
ValueError: max() arg is an empty sequence

**Comment by roseorenbuch** [comment]
This problem should be fixed now with the latest update. Sorry for the delay!
