### ISSUE TITLE
[KeyError] arcasHLA `convert` - using "group"

### ISSUE THREAD

**Issue by jinhys** [RabadanLab/arcasHLA#122]
Hi, I'm getting KeyErrors when I run `arcasHLA convert` using the `-r` parameter like the commands as follows:
```
./arcasHLA convert -r p-group <genotypes.tsv> <outfile.tsv>
./arcasHLA convert -r g-group <genotypes.tsv> <outfile.tsv>
```

#### 1. error message from running `-r p-group`:
```
Traceback (most recent call last):
  File "/home/user/tool/arcasHLA/arcasHLA_master/scripts/convert.py", line 196, in <module>
    genotypes[subject][gene] = convert_allele(allele, resolution)
  File "/home/user/tool/arcasHLA/arcasHLA_master/scripts/convert.py", line 98, in convert_allele
    if allele in p_group[i]:
KeyError: 3
```

#### 2. error message from running `-r g-group`:
```
Traceback (most recent call last):
  File "/home/user/tool/arcasHLA/arcasHLA_master/scripts/convert.py", line 196, in <module>
    genotypes[subject][gene] = convert_allele(allele, resolution)
  File "/home/user/tool/arcasHLA/arcasHLA_master/scripts/convert.py", line 90, in convert_allele
    if allele in g_group[i]:
KeyError: 3
```

*For your reference, these commands work well without any errors:
```
./arcasHLA convert -r 1 <genotypes.tsv> <outfile.tsv>
./arcasHLA convert -r 2 <genotypes.tsv> <outfile.tsv>
./arcasHLA convert -r 3 <genotypes.tsv> <outfile.tsv>
```

It would be greatly appreciated if you could fix these KeyErrors! - Please let me know if you need further details.

**Comment by jinhys** [comment]
Hi @abuendia - If you're available, could you please take a look at these KeyErrors? Thank you!

**Comment by jinhys** [comment]
Hi @abuendia, thanks for fixing this issue. I pulled the latest version (`v0.5.1`) - Now I can generate the output files (both p-group and g-group) successfully using this version. Thank you!
