### ISSUE TITLE
TypeError: only integer scalar arrays can be converted to a scalar index

### ISSUE THREAD

**Issue by Weiyifan** [RabadanLab/arcasHLA#126]
./arcasHLA reference --version 3.24.0

there is 

Traceback (most recent call last):
  File "/***/arcasHLA-master/scripts/reference.py", line 580, in <module>
    build_fasta()
  File "/***/arcasHLA-master/scripts/reference.py", line 443, in build_fasta
    build_complete(allele)
  File "/***/arcasHLA-master/scripts/reference.py", line 332, in build_complete
    seq = seq[:exon_length - (stop - start) + 1]
TypeError: only integer scalar arrays can be converted to a scalar index

**Comment by mattzano** [comment]
same issue here... any hint on how to solve it?

**Comment by NicholasDickel** [comment]
I had the same issue when I just installed with conda like this:
conda install arcas-hla -c bioconda -c conda-forge

Solution:
Make environment with correct dependencies first, then install arcas-hla:

conda env create -f environment.yml
conda activate arcas-hla
conda install arcas-hla -c bioconda -c conda-forge

Hope this helps.

**Comment by dd-lybh** [comment]
same issue

**Comment by zjsyj** [comment]
Thanks, this works for me.

But, when run arcasHLA reference --update will raise errors now since https://github.com/ANHIG/IMGTHLA rename hla.dat to hal.dat.zip

so after doing operations above, you have to **unzip the hal.dat.zip manually**
