### ISSUE TITLE
No HLA name file

### ISSUE THREAD

**Issue by arghdan** [RabadanLab/arcasHLA#130]
When running "arcas genotype fastq1 fastq2" I consistently get the error that there is no such file or directory for hla_nom_p.txt. Specifically " No such file or directory: 'Desktop/anaconda3/share/arcas-hla-0.6.0-1/scripts/../dat/IMGTHLA/wmda/hla_nom_p.txt' "

Similarly when I try to update the HLA file: using "arcasHLA reference --update ", I get the same error

Specifically, the full output is:

arcasHLA reference --update
Traceback (most recent call last):
File "/Desktop/anaconda3/share/arcas-hla-0.6.0-1/scripts/reference.py", line 568, in
build_convert(False)
File "/Desktop/anaconda3/share/arcas-hla-0.6.0-1/scripts/reference.py", line 482, in build_convert
p_group = process_hla_nom(hla_nom_p)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Desktop/anaconda3/share/arcas-hla-0.6.0-1/scripts/reference.py", line 236, in process_hla_nom
for line in open(hla_nom, 'r', encoding='UTF-8'):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by sai-syngenta** [comment]
Please try using docker containers: docker pull jfx319/arcashla

**Comment by asaksager** [comment]
I have the same error when installing the Conda enviroment as described and running 
`arcasHLA reference --update`
and 
`arcasHLA reference --rebuild`

If this is no longer the correct method to installing could you update/remove that from the README?
