### ISSUE TITLE
Error: kallisto index file not found hla_partial.idx

### ISSUE THREAD

**Issue by nellykan** [RabadanLab/arcasHLA#25]
Hi, 
I am trying to replicate the test as explained in the README. The genotyping gives the expected results in test.genotype.json, however when I proceed to the partial typing I get the following error:

```
[alignment] Analyzing read length
[alignment] Pseudoaligning with Kallisto: 

	kallisto pseudo -i arcasHLA-0.2.0/scripts/../dat/ref/hla_partial.idx -t 8 -o /tmp/arcas_c637d791-c0d7-4f56-a472-1f5c0b0a41d0/ test/output/test.extracted.1.fq.gz test/output/test.extracted.2.fq.gz

	
	Error: kallisto index file not found arcasHLA-0.2.0/scripts/../dat/ref/hla_partial.idx
	
	
[alignment] Processing pseudoalignment
Traceback (most recent call last):
  File "arcasHLA-0.2.0/scripts/partial.py", line 485, in <module>
    args.threads, True)
  File "arcasHLA-0.2.0/scripts/align.py", line 277, in get_alignment
    exon_combos)
  File "arcasHLA-0.2.0/scripts/align.py", line 171, in process_partial_counts
    with open(count_file,'r', encoding='UTF-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/arcas_c637d791-c0d7-4f56-a472-1f5c0b0a41d0/pseudoalignments.tsv'
```
Indeed the hla_partial.idx file is missing. Should this file have been downloaded with the rest when executing `./arcasHLA reference --version 3.24.0` or is the user expected to create it?

Thanks

**Comment by nellykan** [comment]
It seems that I was calling `./arcasHLA reference --version 3.24.0` without enough memory.
