### ISSUE TITLE
./arcasHLA reference --update failed

### ISSUE THREAD

**Issue by egoecho** [RabadanLab/arcasHLA#32]
```
$ ./arcasHLA reference --update       
Traceback (most recent call last):
  File "/.../arcasHLA/scripts/reference.py", line 534, in <module>                                                               
    build_convert(False)
  File "/.../arcasHLA/scripts/reference.py", line 462, in build_convert                                                          
    p_group = process_hla_nom(hla_nom_p)
  File "/.../arcasHLA/scripts/reference.py", line 232, in process_hla_nom                                                        
    for line in open(hla_nom, 'r', encoding='UTF-8'):
FileNotFoundError: [Errno 2] No such file or directory: '/.../arcasHLA/scripts/../dat/IMGTHLA/wmda/hla_nom_p.txt'                

$ ./arcasHLA reference --rebuild
Traceback (most recent call last):
  File "/.../arcasHLA/scripts/reference.py", line 539, in <module>                                                               
    build_convert()
  File "/.../arcasHLA/scripts/reference.py", line 462, in build_convert                                                          
    p_group = process_hla_nom(hla_nom_p)
  File "/.../arcasHLA/scripts/reference.py", line 232, in process_hla_nom                                                        
    for line in open(hla_nom, 'r', encoding='UTF-8'):
FileNotFoundError: [Errno 2] No such file or directory: '/.../arcasHLA/scripts/../dat/IMGTHLA/wmda/hla_nom_p.txt' 
```

**Comment by tpereachamblee** [comment]
Thank you for using our tool. We cannot replicate the issue you are posting here. Please check if the dependencies are properly installed, and post the exact command as well as the output in that case.

**Comment by yingchen69** [comment]
Hi guys,

I just built arcasHLA and got similar error when I tried to fetch IMGT/HLA database version 3.24.0:

    [yc790]$ arcasHLA reference --version 3.24.0
    Traceback (most recent call last):
      File "/cache/home/yc790/apps/arcasHLA/scripts/reference.py", line 546, in <module>
        build_fasta()
      File "/cache/home/yc790/apps/arcasHLA/scripts/reference.py", line 414, in build_fasta
        utrs, exons, final_exon_length) = process_hla_dat()
      File "/cache/home/yc790/apps/arcasHLA/scripts/reference.py", line 132, in process_hla_dat
        with open(hla_dat, 'r', encoding='UTF-8') as file:
    FileNotFoundError: [Errno 2] No such file or directory: 
    '/cache/home/yc790/apps/arcasHLA/scripts/../dat/IMGTHLA/hla.dat'

Any suggestion?

Thanks a lot for the help!

Best,

Ying

**Comment by TheSallyGardens** [comment]
Hi,I have the same problem!

**Comment by tpereachamblee** [comment]
Thank you all for using our tool.

This error occurs when Git Large File Storage (git lfs) is not properly installed and configured before using our tool. For an example of how to properly install and configure git lfs on Debian/ Ubuntu, please refer to our [Dockerfile](https://github.com/RabadanLab/arcasHLA/blob/master/Docker/Dockerfile) (lines 69-71 at the time of writing this). Depending on your operating system and distribution, you may need to modify some or all of the commands. Please consult the proper documentation for your system.
