### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by jerryyuezhang** [RabadanLab/arcasHLA#37]
I was trying to run arcasHLA but received this error:
Traceback (most recent call last):
  File "/home/yzx5896/.conda/envs/arcasHLA/bin/scripts/genotype.py", line 674, in <module>
    check_ref()
  File "/home/yzx5896/.conda/envs/arcasHLA/bin/scripts/reference.py", line 80, in check_ref
    build_convert(False)
  File "/home/yzx5896/.conda/envs/arcasHLA/bin/scripts/reference.py", line 462, in build_convert
    p_group = process_hla_nom(hla_nom_p)
  File "/home/yzx5896/.conda/envs/arcasHLA/bin/scripts/reference.py", line 232, in process_hla_nom
    for line in open(hla_nom, 'r', encoding='UTF-8'):
FileNotFoundError: [Errno 2] No such file or directory: '/home/yzx5896/.conda/envs/arcasHLA/bin/scripts/../dat/IMGTHLA/wmda/hla_nom_p.txt'

Where could I get the IMGTHLA/wmda/hla_nom_p.txt' file? I would appreciate your help.

**Comment by tpereachamblee** [comment]
Thank you for using our tool. Please see the explanation provided in issue #32.
