### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by eegk** [RabadanLab/arcasHLA#52]
Hi,

When running genotype I get the following error:

arcasHLA genotype test.extracted.1.fq.gz test.extracted.2.fq.gz

Traceback (most recent call last):
  File "/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/genotype.py", line 674, in <module>
    check_ref()
  File "/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/reference.py", line 80, in check_ref
    build_convert(False)
  File "/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/reference.py", line 462, in build_convert
    p_group = process_hla_nom(hla_nom_p)
  File "/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/reference.py", line 232, in process_hla_nom
    for line in open(hla_nom, 'r', encoding='UTF-8'):
FileNotFoundError: [Errno 2] No such file or directory: '/hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/../dat/IMGTHLA/wmda/hla_nom_p.txt'

The log shows that the error is at git lsf clone command
git lfs clone https://github.com/ANHIG/IMGTHLA.git /hpc/packages/minerva-centos7/arcashla/0.2.0/arcasHLA-0.2.0/scripts/../dat/IMGTHLA/

git: 'lfs' is not a git command. See 'git --help'.

How I can deal with this error?.

Thank you!

**Comment by tpereachamblee** [comment]
Thank you for using our tool. Please see the explanation provided in issue #32
