### ISSUE TITLE
./arcasHLA reference --update fires an error

### ISSUE THREAD

**Issue by OrielResearchCure** [RabadanLab/arcasHLA#76]
Hello all,

I would like to try the arcas-HLA tool. I hope that you will be able to help me with the installation/execution.
I am working with the following OS on a cloud machine: Debian GNU/Linux 10 (buster).
I tried to install it with Conda and it didn’t work for me (https://anaconda.org/bioconda/arcas-hla)
The following error is after manually installing the dependencies and running: git clone https://github.com/roseorenbuch/arcasHLA.git 

when running the reference --update command. this is the error

```
Traceback (most recent call last):
  File "/home/../../../../../../STEP_4_HLA_TYPING/arcasHLA/scripts/reference.py", line 482, in <module>
    build_fasta()
  File "/home/../../../../../..//STEP_4_HLA_TYPING/arcasHLA/scripts/reference.py", line 371, in build_fasta
    utrs, exons, final_exon_length) = process_hla_dat()
  File "/home/../../../../../..//STEP_4_HLA_TYPING/arcasHLA/scripts/reference.py", line 131, in process_hla_dat
    with open(hla_dat, 'r', encoding='UTF-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/../../../../../../STEP_4_HLA_TYPING/arcasHLA/scripts/../dat/IMGTHLA/hla.dat'
```

under dat folder, I see the following folders:
```
ls ./dat/
info  ref
```

under the ref folder, I see:
```
ls ./dat/ref/
GRCh38.chr6.HLA.fasta  GRCh38.chr6.fasta  GRCh38.chr6.noHLA.fasta  allele_groups.p  cDNA.p  cDNA.single.p  hla_transcripts.json
```

how to include the IMGTHLA folder?

Many thanks for your help,
Eila

**Comment by OrielResearchCure** [comment]
Based on previous issues that were reported, I reinstalled the git-lfs package.
The issue was not resolved by that.
Please let me know if you have any other idea how to resolve that.
Thanks,
Eila

**Comment by tpereachamblee** [comment]
Thank you for using our tool. We cannot replicate the issue you are posting here. We tested the conda environment using the following commands which worked as expected:

```
conda install -c bioconda arcas-hla
git lfs install 
arcasHLA reference --update -v
```

Please try these commands and copy the exact output of each here if there are any outstanding issues.

Moreover, as per the most recent tagged release [v0.4.0](https://github.com/RabadanLab/arcasHLA/releases/tag/v0.4.0) there is no longer any need to use the code base located here https://github.com/roseorenbuch/arcasHLA.git 

Please clone and use this repository as such: `git clone https://github.com/RabadanLab/arcasHLA.git`

**Comment by tpereachamblee** [comment]
Closing issue due to inactivity.

**Comment by OrielResearchCure** [comment]
Thank you. 
I was able to install it with conda. 
I gad to make sure to use the python 3.6 and follow the commands that you listed
