### ISSUE TITLE
Error in customize function

### ISSUE THREAD

**Issue by ttab963** [RabadanLab/arcasHLA#79]
Hello, team. 

First I want to say thanks to this nice tool. 
Other functions in this tool work good like _genotype_. in my single cell RNA sequencing data (+single end). 
I downloaded this tool from conda.

But when I tried to use _customize_ for quantification, some error came out.
This is the code.
~~~
arcasHLA customize \
--genotype OM-HS-063-C8-F.partial_genotype.json \
--transcriptome chr6 \
-o ./ref 
~~~
And this is the error.
~~~
None
{'A1': 'A*30:01', 'A2': 'A*24:02', 'B1': 'B*15:01', 'B2': 'B*13:02', 'C1': 'C*06:287', 'C2': 'C*01:02', 'DPB11': 'DPB1*02:01', 'DPB12': 'DPB1*05:01', 'DQA11': 'DQA1*01:71', 'DQA12': 'DQA1*02:01', 'DQB11': 'DQB1*02:02', 'DQB12': 'DQB1*06:02', 'DRB11': 'DRB1*07:01', 'DRB12': 'DRB1*15:01'}
Traceback (most recent call last):
  File "/data/anaconda3/envs/HLA/share/arcas-hla-0.4.0-0/scripts/customize.py", line 317, in <module>
    build_custom_reference(subject, genotype, args.grouping, args.transcriptome, temp)
  File "/data/anaconda3/envs/HLA/share/arcas-hla-0.4.0-0/scripts/customize.py", line 92, in build_custom_reference
    transcriptome.append(dummy_HLA_dict[transcript])
KeyError: 'ENST00000437811.1'
~~~

For explanation, ENST00000437811.1 is HLA-DPA1-243 from ensembl but I'm not sure about this is important or not.
Version of my python is 3.8.12 because of [this ](https://github.com/roseorenbuch/arcasHLA-quant/issues/6#issuecomment-791223110)issue. 
If you need any additional information, I will provide.

Thanks to your kind help.

**Comment by tpereachamblee** [comment]
Thank you for your interest in and for using our tool! This issue likely has to do with using a IMGT/HLA reference version later than 3.32.0 owing to the static cDNA file in `/dat/ref/` which has not been updated recently. Please try rolling by the reference and repeating the genotyping, then use that `genotype.json` for the `custom` module.

**Comment by mdribus** [comment]
Hi, I am having the same problem described in the original question. I have tried using IMGT/HLA reference versions 3.24.0, 3.32.0, and ./arcasHLA reference --update. I update the extract and genotyping each time, but when I run "customize" on the genotype.json file, I get the key error. The error is the same no matter which reference I use.

**Comment by Portulaca666** [comment]
> Hello, team.
> 
> First I want to say thanks to this nice tool. Other functions in this tool work good like _genotype_. in my single cell RNA sequencing data (+single end). I downloaded this tool from conda.
> 
> But when I tried to use _customize_ for quantification, some error came out. This is the code.
> 
> ```
> arcasHLA customize \
> --genotype OM-HS-063-C8-F.partial_genotype.json \
> --transcriptome chr6 \
> -o ./ref 
> ```
> 
> And this is the error.
> 
> ```
> None
> {'A1': 'A*30:01', 'A2': 'A*24:02', 'B1': 'B*15:01', 'B2': 'B*13:02', 'C1': 'C*06:287', 'C2': 'C*01:02', 'DPB11': 'DPB1*02:01', 'DPB12': 'DPB1*05:01', 'DQA11': 'DQA1*01:71', 'DQA12': 'DQA1*02:01', 'DQB11': 'DQB1*02:02', 'DQB12': 'DQB1*06:02', 'DRB11': 'DRB1*07:01', 'DRB12': 'DRB1*15:01'}
> Traceback (most recent call last):
>   File "/data/anaconda3/envs/HLA/share/arcas-hla-0.4.0-0/scripts/customize.py", line 317, in <module>
>     build_custom_reference(subject, genotype, args.grouping, args.transcriptome, temp)
>   File "/data/anaconda3/envs/HLA/share/arcas-hla-0.4.0-0/scripts/customize.py", line 92, in build_custom_reference
>     transcriptome.append(dummy_HLA_dict[transcript])
> KeyError: 'ENST00000437811.1'
> ```
> 
> For explanation, ENST00000437811.1 is HLA-DPA1-243 from ensembl but I'm not sure about this is important or not. Version of my python is 3.8.12 because of [this ](https://github.com/roseorenbuch/arcasHLA-quant/issues/6#issuecomment-791223110)issue. If you need any additional information, I will provide.
> 
> Thanks to your kind help.

Have you already resolved  this problem ？ 
My version is  IPD-IMGT/HLA 3.54.0
and   I got  the same error .
`None
{'B1': 'B*51:01', 'B2': 'B*07:386N', 'C1': 'C*07:02', 'C2': 'C*15:02', 'DPB11': 'DPB1*04:01', 'DPB12': 'DPB1*04:01', 'DQA11': 'DQA1*01:03', 'DQA12': 'DQA1*01:03', 'DQB11': 'DQB1*06:03', 'DQB12': 'DQB1*06:112N', 'DRB11': 'DRB1*15:01', 'DRB12': 'DRB1*15:01'}
Traceback (most recent call last):
  File "/gpfs1/xjhuang_pkuhpc/tools/arcasHLA/scripts/customize.py", line 317, in <module>
    build_custom_reference(subject, genotype, args.grouping, args.transcriptome, temp)
  File "/gpfs1/xjhuang_pkuhpc/tools/arcasHLA/scripts/customize.py", line 92, in build_custom_reference
    transcriptome.append(dummy_HLA_dict[transcript])
KeyError: 'ENST00000425337.1'
`

**Comment by Lies-VO** [comment]
https://github.com/RabadanLab/arcasHLA/issues/79#issuecomment-1059555697

This solution didn't work for me, is there anything else I can try?
Thank you!

**Comment by dd-lybh** [comment]
> [#79 (comment)](https://github.com/RabadanLab/arcasHLA/issues/79#issuecomment-1059555697)
> 
> This solution didn't work for me, is there anything else I can try?这个解决方案对我无效，还有其他可以尝试的方法吗？ Thank you!  谢谢！

Hi , I was also wondering if you made any process on this? Thanks!

**Comment by dd-lybh** [comment]
I've fixed it.
Whether you use conda to download or directly use git clone, if Git LFS is not installed in your environment, the following files - GRCh38.all.noHLA.fasta, GRCh38.chr6.HLA.fasta, and GRCh38.chr6.noHLA.fasta - will only download Git LFS placeholder files, resulting in failure to properly download the reference genome (you can check the file sizes).

Solution
Either replace these three files or clone the arcas-hla repository in an environment with Git LFS installed.

**Comment by jonasfreimuth** [comment]
Also currently dealing with this problem, except that as far as I can tell the bandwidth budget for LFS files has run out for this repo (or whatever unit of billing is applicable) and the files in question cannot be downloaded.

<details>
<summary>This is how that looks like for me</summary>

```log
$ git clone https://github.com/RabadanLab/arcasHLA
Cloning into 'arcasHLA'...
remote: Enumerating objects: 745, done.
remote: Counting objects: 100% (115/115), done.
remote: Compressing objects: 100% (46/46), done.
remote: Total 745 (delta 89), reused 69 (delta 69), pack-reused 630 (from 2)
Receiving objects: 100% (745/745), 11.18 MiB | 23.94 MiB/s, done.
Resolving deltas: 100% (435/435), done.
Downloading dat/ref/GRCh38.all.noHLA.fasta (341 MB)
Error downloading object: dat/ref/GRCh38.all.noHLA.fasta (d6b75ae): Smudge error: Error downloading dat/ref/GRCh38.all.noHLA.fasta (d6b75ae7a1f7513917047acd642f20e8d9ed510c269a68d50aa1f9e20952a84d): batch response: This repository exceeded its LFS budget. The account responsible for the budget should increase it to restore access.

Errors logged to '/tmp/tmp.ki9oW5FBGC/arcasHLA/.git/lfs/logs/20250621T144830.396655277.log'.
Use `git lfs logs last` to view the log.
error: external filter 'git-lfs filter-process' failed
fatal: dat/ref/GRCh38.all.noHLA.fasta: smudge filter lfs failed
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

</details>

On my [fork](https://github.com/TRON-Private/arcasHLA/tree/remove-need-for-lfs) I have packaged the files into a compressed tar file and decompress them on demand. If desired I could open a PR for this as well.
