### ISSUE TITLE
Bypass errors creating reference for quant

### ISSUE THREAD

**Issue by Evan-SF** [RabadanLab/arcasHLA#82]
Hi, 
First at all, thank you for this wonderful tool. Unfortunetely, I'm encountering some errors as other users and I didn't find any good solution to solve them.

In fact, after install arcasHLA with Conda (the latest version) with this command : conda install -c bioconda arcas-hla (version 0.5) I didn't succeed to create a reference with the customize parameter. I would like to use it with quant parameter later. I'm facing dthe Bio.Alphabet error 

`
Traceback (most recent call last):
File "/Home/Users/user/.conda/envs/arcasHLA_P36/share/arcas-hla-0.5.0-0/scripts/customize.py", line 43, in <module>
from Bio.Alphabet import generic_dna
File "/Home/Users/user/.local/lib/python3.8/site-packages/Bio/Alphabet/__init__.py", line 20, in <module>
raise ImportError(
ImportError: Bio.Alphabet has been removed from Biopython. In many cases, the alphabet can simply be ignored and removed from scripts. In a few cases, you may need to specify the "molecule_type" as an annotation on a SeqRecord for your script to work correctly. Please see https://biopython.org/wiki/Alphabet for more information.
`

After google the error I downgrade BioPython to 1.76 and it works but I'm encountering the same error as in this issue : https://github.com/RabadanLab/arcasHLA/issues/79 

I try many things like update and downgrade IMGT db for arcasHLA but it doesn't work. 

Do you have any ideas please to resolve these problems ? 

Thank you,
Evan

**Comment by naity2** [comment]
Hi @Evan-SF, I was wondering if you made any process on this? Thanks!

**Comment by Evan-SF** [comment]
> Hi @Evan-SF, I was wondering if you made any process on this? Thanks!

Hi, sorry for the delay of my reply. I made some graphs with results ! Not exactly as on the paper. I will show some here as soon as possible :)

**Comment by Portulaca666** [comment]
Hi , I was  also   wondering if you made any process on this? Thanks!
